version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: >-
    nuget restore

    . "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\sn.exe" -k ./PdfAValidator/PdfAValidator.snk
build:
  project: PdfAValidator.sln
  publish_aspnet_core: true
  verbosity: minimal
artifacts:
- path: '**\PdfAValidator.*.nupkg'
deploy:
- provider: GitHub
  auth_token:
    secure: T0ZNNOTk6DIT8ag+vBbSZjYtTLJiSgrMg4kp2h9/WBmj2VGKhQpLq2RwrA8yjbdZ
  prerelease: true
- provider: NuGet
  api_key:
    secure: uam/dXnhJv544YdAQNP+mKC9fkL7UFQydK/55TWjozWEswDWNUBh/Mq/WLv8Fa8U