version: 2.1.{build}
image:
  - Visual Studio 2019
  - Ubuntu
skip_tags: true
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
  - ps: >-
      nuget restore

build:
  project: PdfAValidator.sln
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\PdfAValidator.*.nupkg'
deploy:
  - provider: GitHub
    auth_token:
      secure: T0ZNNOTk6DIT8ag+vBbSZjYtTLJiSgrMg4kp2h9/WBmj2VGKhQpLq2RwrA8yjbdZ
    prerelease: true
  - provider: NuGet
    api_key:
      secure: CTISdGCfnpyC7Rh5vs1pgbuISrkWF34sot0SyVgvu0HQxhNNd+V0Gc4MS+rtJttB
    on:
      branch: main
